### ISSUE TITLE
Walk-through mode stopped working for targets other than citizens

### ISSUE THREAD

**Issue by fransgandersson** [will258012/CitiesSkylines-FPSCamera-Continued#2]
## Bug Description
Walk-through mode is only able to find citizens. Buses, services vehicles, cargo vehicles not found. 
This used to work until very recently and I've not changed my set up.

## Bug Reproduction
- Start with default mod config
- Change mod config for walk-through mode to only include Public transit vehicles, Service vehicles &  Cargo vehicles, 
- Make sure you can see buses, trains and garbage trucks and cargo trucks driving around
- Click on camera icon followed by "Start Walk-Through"
- There is a slight zoom-in but no vehicles are followed. 
- Log says "[Warning] no target for Walk-Thru mode"
- NB! When citizens are enabled in the mod config, it still doesn't work always but it does at least occasionally find a citizen to follow.
- Another issue (which I suspect has the same root cause) is that switch on secondary mouse click almost never works.
- I'm on a very small city; is there a minimum number of targets that have to be active on the map for the walk-through mode to find a target?

## Expected behavior
Walk-Through mode finds one of the active targets when started and on secondary click.

## Log files
Please attach the relevant part of the log file from both `.../Steam/steamapps/common/Cities_Skylines/FPSCamera.log` and `.../Cities_Skylines/Ci
[output_log.txt](https://github.com/user-attachments/files/15521773/output_log.txt)
ties_Data/output_log.txt`
[FPSCamera.log](https://github.com/user-attachments/files/15521772/FPSCamera.log)

**Comment by will258012** [comment]
Hello! A new testing version is available on [Github](https://github.com/will258012/CitiesSkylines-FPSCamera-Continued/releases/tag/v2.4.0-b1) and [Steam workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=3281544449).
Please download the new version and see if your issue has been resolved.

**Comment by fransgandersson** [comment]
Yes, working better, thank you. I suspect the issue was more with having very few (~10-20) vehicles to choose from as with a bigger city it finds vehicles also with the stable version.

**Comment by will258012** [comment]
In the https://github.com/will258012/CSkyL/commit/5d8c76b1027e4e7959e6a669d126d3bc396ebbb2 commit:
The purpose of the function should be to iterate through the vehicle ids in the city (from first to last) and return the vehicles that match the criteria.
However, `manager.m_vehicleCount` is wrong - it is the valid total number of vehicles in the city, not the maximum assignable number `manager.m_vehicles.m_buffer.Length - 1`.
This is probably an oversight on the part of the author when writing the code. There was a similar issue for pedestrians (fixed).
As an analogy: if you are in a small city, then the valid number of vehicles is only about a hundred. If the id of the vehicle you want happens to be higher than that, the mod won't be able to find it.
In a large city, where the valid number of vehicles is high enough (even close to the limit just above), then the chances of the mod not finding the vehicle are reduced and the problem is less noticeable.
